export * from './Hero'
export * from './Categories'
export * from './Nav'
export * from './ProductPreview'
export * from './About'
export * from './Footer'
export { default as CategoryTitle } from './CategoryTitle'
