export * from './Hero'
export * from './Categories'
export * from './Nav'
export * from './ProductHighlight'
export * from './About'
export * from './Footer'
export * from './Gallery'
export { default as CategoryTitle } from './CategoryTitle'
export { default as ProductsPreview } from './ProductsPreview'
export { default as Cart } from './Cart'
