import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Morbi interdum mollis sapien</h1>
        <h2>Morbi interdum mollis sapien</h2>
        <h3>Morbi interdum mollis sapien</h3>
        <h4>Morbi interdum mollis sapien</h4>
        <h5>Morbi interdum mollis sapien</h5>
        <h6>Morbi interdum mollis sapien</h6>
        <p className="overline">Morbi interdum mollis sapien</p>
        <p className="sub-title">Morbi interdum mollis sapien</p>
      </main>
    </div>
  )
}
